page_title                                : Countlit

ios_app_id                                : 1525265985

app_icon                                  : /assets/appicon.png
app_name                                  : Countlit
app_description                           : Create and share beautiful countdowns to anticipate the best moments in life!
enable_smart_app_banner                   : true
appstore_link                             : https://apps.apple.com/us/app/id1525265985

your_name                                 : Omar Albeik
your_link                                 : https://omaralbeik.com
twitter_username                          : omaralbeik
github_username                           : omaralbeik

features                                  :

  - title                                 : Create Countlits
    description                           : Use your camera, photos library, or a wide collection of curated photos.
    fontawesome_icon_name                 : plus
    
  - title                                 : Customize Your Countlits
    description                           : Choose from a wide collection of curated fonts and colors.
    fontawesome_icon_name                 : star

  - title                                 : Share Your Best Moments
    description                           : Share your countlits with the world!
    fontawesome_icon_name                 : share

  - title                                 : See Popular Countlits
    description                           : Learn more about hundreds of popular countlits from around the world!
    fontawesome_icon_name                 : fire

topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"


####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

url: "//countlit.com"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown